apiVersion: skaffold/v4beta14
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
# Default local build & deploy    
build:
  local:
    push: false
  artifacts:
    - image: richdgo4/auth
      context: .
      docker:
        dockerfile: auth/Dockerfile
      sync:
        manual:
          - src: "auth/src/**/*.ts"
            dest: "."
    - image: richdgo4/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "pages/**/*.js"
            dest: "."
            
# Expose MongoDB for easier local testing
portForward:
  - resourceType: service
    resourceName: auth-mongo-service
    namespace: default
    port: 27017
    localPort: 27017

profiles:
  # Deploy to GCP
  - name: gcp
    manifests:
      rawYaml:
        - ./infra/k8s-gcp/*
    build:
      local:
        push: true
      artifacts:
        - image: europe-north1-docker.pkg.dev/project-809e066d-e5ea-4d42-aa1/ticketing/auth
          context: .
          docker:
            dockerfile: auth/Dockerfile
          sync:
            manual:
              - src: "auth/src/**/*.ts"
                dest: "."
        - image: europe-north1-docker.pkg.dev/project-809e066d-e5ea-4d42-aa1/ticketing/client
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "pages/**/*.js"
                dest: "."
        - image: europe-north1-docker.pkg.dev/project-809e066d-e5ea-4d42-aa1/ticketing/hedgehog-consultancy
          context: hedgehog-consultancy
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: "."