apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/users/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 3000
      - path: /api/hedgehog/consult
        pathType: ImplementationSpecific
        backend:
          service:
            name: hedgehog-consultancy-service
            port:
              number: 3001
