# NB doesn't have PVC yet!
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      containers:
        - name: orders-mongo
          image: mongo:8
---
apiVersion: batch/v1
kind: Job
metadata:
  name: orders-mongo-index
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: create-index
          image: mongo:8
          command:
            - mongosh
            - mongodb://orders-mongo-service:27017/orders
            - --eval
            - "db.orders.createIndex({ userId: 1 }); db.orders.createIndex({ ticket: 1 })"
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-service
spec:
  type: ClusterIP
  selector:
    app: orders-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
